// SPDX-License-Identifier: MIT
/* Copyright (c) 2023, ARTCOMPILER INC */
//
// L0178 inherits L0000: its Checker/Transformer extend L0000's. Unhandled tags fall
// through to L0000's base handlers via `super`/the shared Visitor dispatch.
//
// No L0178 handlers yet. The dialect's own constructs are the Data API job registry
// (endpoint x action) described in spec/scope.json, and they are not written yet.
// L0003's demo handlers (HELLO/IMAGE/THEME) were removed with its keywords.
//
// When they arrive, follow L0177's shape rather than hand-writing per-construct
// handlers: a single vocabulary module is the source of truth, and the Checker and
// Transformer methods are generated by looping over it. That is what keeps a registry
// of this size honest — and for L0178 the registry is two-level, because the legal
// request fields depend on the (endpoint, action) PAIR, not on the endpoint alone.
import {
  Checker as BaseChecker,
  Transformer as BaseTransformer,
  Compiler,
} from "@graffiticode/l0000";

export class Checker extends BaseChecker {
  [key: string]: any;
}

export class Transformer extends BaseTransformer {
  [key: string]: any;

  PROG(node, options, resume) {
    this.visit(node.elts[0], options, async (e0, v0) => {
      const data = options?.data || {};
      const val = v0.pop();
      // No `_` wrapper: the program result IS the data (carried in the compile envelope's
      // `data` field). Records merge with any input data; scalars/lists pass through as-is.
      const isObject = typeof val === "object" && val !== null && !Array.isArray(val);
      resume(e0, isObject ? { ...val, ...data } : val);
    });
  }
}

export const compiler = new Compiler({
  langID: "0178",
  version: "v0.0.1",
  Checker,
  Transformer,
});
